[package]
name = "search-index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-tfidf = "1.1.1"
serde = "1.0.163"
serde_json = "1.0.96"
