[package]
name = "brianjlogan2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = { version="0.8.2", features=['ssr']}
sycamore-router = "0.9.0-beta.1"