#!/usr/bin/env bash
# Regenerate content/agents/posts-index.md from the posts in content/posts/.
# Run as part of build.sh so the agent-readable index never drifts from the
# actual set of posts on disk.

set -e

OUTPUT="content/agents/posts-index.md"

cat > "$OUTPUT" << 'HEADER'
+++
title = "Posts Index"
date = 2025-02-08
template = "page.html"
[extra]
summary = "Index of all blog posts for AI agents"
+++

# Posts Index

Complete list of all blog posts available in machine-readable format.

This file is generated by `generate-posts-index.sh` - edit the script, not
the file.

**Machine-readable format:**

```nickel
{
  version = "1.0",
  posts = [
HEADER

count=0
# Sort by date desc by reading frontmatter dates
# Build a list of "date|file" pairs so we can sort, then iterate.
mapfile -t entries < <(
    for file in content/posts/*.md; do
        filename=$(basename "$file")
        if [[ "$filename" == "_index"* ]]; then
            continue
        fi
        date_line=$(grep -m 1 "^date = " "$file" || echo "")
        date_val=$(echo "$date_line" | sed -E 's/date = ([0-9TZ:.+-]+).*/\1/')
        echo "${date_val}|${file}"
    done | sort -r
)

for entry in "${entries[@]}"; do
    file="${entry#*|}"
    filename=$(basename "$file")
    slug="${filename%.md}"

    title=$(grep -m 1 '^title = ' "$file" | cut -d'"' -f2)
    date=$(grep -m 1 '^date = ' "$file" | cut -d'=' -f2 | tr -d ' ')
    summary=$(grep -m 1 '^summary = ' "$file" | cut -d'"' -f2)

    if [ -z "$title" ]; then
        continue
    fi

    cat >> "$OUTPUT" << ENTRY
    {
      url = "/agents-md/posts/$filename",
      title = "$title",
      date = "$date",
      summary = "$summary",
    },
ENTRY
    count=$((count+1))
done

cat >> "$OUTPUT" << 'MIDDLE'
  ]
}
```

## All Posts

MIDDLE

for entry in "${entries[@]}"; do
    file="${entry#*|}"
    filename=$(basename "$file")
    slug="${filename%.md}"
    title=$(grep -m 1 '^title = ' "$file" | cut -d'"' -f2)
    if [ -z "$title" ]; then
        continue
    fi
    echo "- [$title](/posts/$slug/)" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'FOOTER'

---

**Navigation:**
- [← Back to Agent Hub](/agents/)
- [← Following List](/agents/following/)
- [← Interested In](/agents/interested/)
- [Raw markdown files →](/agents-md/posts/)
FOOTER

echo "  ✓ Generated $OUTPUT with $count posts"
